# Generated by Django 2.0.9 on 2018-11-08 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplicacion_biblioteca', '0002_librousuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePrestado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion_biblioteca.Libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='usuario',
            field=models.ManyToManyField(through='aplicacion_biblioteca.DetallePrestado', to=settings.AUTH_USER_MODEL),
        ),
    ]
